export const GET_SNEAKERS = 'GET_SNEAKERS';
export const GET_SNEAKER_DETAIL = 'GET_SNEAKER_DETAIL';
export const LOADING = 'LOADING';
export const RESET_DETAIL = 'RESET_DETAIL';
export const GET_ALL_SNEAKERS = 'GET_ALL_SNEAKERS';
