export const GET_SNEACKERS = 'GET_SNEACKERS';
export const GET_SNEAKER_DETAIL = 'GET_SNEAKER_DETAIL';
export const LOADING = 'LOADING';
export const RESET_DETAIL = 'RESET_DETAIL';
export const GET_ALL_SNEACKERS = 'GET_ALL_SNEACKERS';
